import PDFDocument from "pdfkit";

const generatePdf = async (data) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: "A4",
            margin: 50,
            info: {
                Author: "CortextAI",
                Title: data.title,
                Creator: "CortextAI"
            }
        });

        const chunks = [];

        doc.on("data", (chunk) => chunks.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", (err) => reject(err));

        // ---- Title ----
        doc.fontSize(28)
            .text(data.title || "", { align: "center" })
            .fillColor("#111827");

        // ---- Subtitle ----
        if (data.subtitle) {
        doc.moveDown(0.5);
        }
         doc.moveDown(0.3)
                .fontSize(12)
                .fillColor("#555555")
                .text(data.subtitle, { align: "center" });
            doc.fillColor("#000000");
        



        // Horizontal rule under header
        // doc .moveTo(doc.page.margins.left, doc.y)
        //     .lineTo(doc.page.width - doc.page.margins.right, doc.y)
        //     .strokeColor("#cccccc")
        //     .stroke();

        doc.moveDown(2);

        // ---- Sections ----
        const sections = Array.isArray(data.sections) ? data.sections : [];

        sections.forEach((section, idx) => {
            // Add a bit of space before each new section (except handle page breaks)
            if (idx > 0) doc.moveDown(1);

            // Heading
            if (section.heading) {
                doc.fontSize(18)
                    .fillColor("#111827")
                    .text(section.heading, { align: "left" });
                doc.moveDown(0.5);
            }

            // Points (bulleted list)
            const points = Array.isArray(section.points) ? section.points : [];


            points.forEach((point) => {
                // Check if we're near the bottom of the page; add new page if needed
                if (doc.y > doc.page.height - doc.page.margins.bottom - 40) {
                    doc.addPage();
                }

                doc.text(`•  ${point}`, {
                    align: "left",
                    indent: 10,
                    lineGap: 5
                });
            });
        });
        doc.fontSize(10)
        .text("Generated By CortextAI")
        .fillColor("#111827")

        doc.end();
    });
};

export default generatePdf;